"""Add color and selected_theme_ids fields to Team model for Round 3

Revision ID: 151a691eefd6
Revises: 
Create Date: 2026-05-12 13:03:45.920353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151a691eefd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we can't change column type with ALTER COLUMN
    # Both columns already exist in the database:
    # - color: VARCHAR (already exists)
    # - selected_theme_ids: TEXT (SQLite treats TEXT as JSON affinity)
    # 
    # The migration is a no-op because the schema already matches requirements
    # SQLAlchemy's JSON() type works with TEXT columns in SQLite
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'selected_theme_ids',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('memory_grid_rounds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_session_id', sa.INTEGER(), nullable=True),
    sa.Column('memory_grid_id', sa.INTEGER(), nullable=True),
    sa.Column('current_team_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['memory_grid_id'], ['memory_grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_grid_rounds_id', 'memory_grid_rounds', ['id'], unique=False)
    op.create_table('grid_cells',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('memory_grid_id', sa.INTEGER(), nullable=True),
    sa.Column('row', sa.INTEGER(), nullable=True),
    sa.Column('col', sa.INTEGER(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('assigned_team_id', sa.INTEGER(), nullable=True),
    sa.Column('answered_by_team_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['answered_by_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['assigned_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['memory_grid_id'], ['memory_grids.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grid_cells_id', 'grid_cells', ['id'], unique=False)
    op.create_table('memory_grids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_session_id', sa.INTEGER(), nullable=True),
    sa.Column('rows', sa.INTEGER(), nullable=True),
    sa.Column('cols', sa.INTEGER(), nullable=True),
    sa.Column('current_turn', sa.INTEGER(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_grids_id', 'memory_grids', ['id'], unique=False)
    # ### end Alembic commands ###
