"""add started field to game_sessions

Revision ID: 70fc813ad257
Revises: f91ecd2421ca
Create Date: 2026-07-27 21:22:28.708917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fc813ad257'
down_revision: Union[str, None] = 'f91ecd2421ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ajoutée nullable d'abord pour pouvoir peupler les lignes existantes,
    # puis verrouillée à NOT NULL : le modèle SQLAlchemy et le schéma Pydantic
    # (`started: bool`, non optionnel) supposent une valeur toujours présente
    # — une ligne NULL ferait échouer la validation de réponse (trouvé en revue).
    op.add_column('game_sessions', sa.Column('started', sa.Boolean(), nullable=True, server_default=sa.false()))
    # Les parties existantes avant cette migration n'ont jamais connu de salle
    # d'attente : elles étaient déjà en cours, donc marquées "started" pour ne
    # pas bloquer les joueurs déjà en partie.
    op.execute("UPDATE game_sessions SET started = 1")
    with op.batch_alter_table('game_sessions') as batch_op:
        batch_op.alter_column('started', existing_type=sa.Boolean(), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'started')
    # ### end Alembic commands ###
